# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PyCombinator
author: Henrik Finsberg
copyright: "2023"
only_build_toc_files: true



# Information about where the book exists on the web
repository:
  url: https://github.com/finsberg/pycombinator # Online location of your book
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  binderhub_url: "https://mybinder.org"

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify

sphinx:
  config:
    html_last_updated_fmt: "%b %d, %Y"
    autoapi_dirs: ['src']
    # Ref: https://github.com/executablebooks/sphinx-external-toc/issues/36
    suppress_warnings: ["etoc.toctree"]

  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.autosummary'
  - 'autoapi.extension'

exclude_patterns: [".pytest_cache/*"]
